# -*- coding: utf-8 -*-
"""Untitled94.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNu1ECb5UK24HFHbGQYAXJY8iH6kYZn7

## 1. Data Loading

First, we need to load the two datasets: the Bitcoin Market Sentiment Dataset and the Historical Trader Data from Hyperliquid.

**Instructions:**
1.  Download the historical data from the Google Drive link provided in the prompt.
2.  Extract the CSV files (if they are in an archive).
3.  Upload the CSV files to your Colab environment (e.g., drag and drop them into the file browser on the left sidebar).
4.  Update the `pd.read_csv()` calls below with the correct filenames once uploaded.
"""

import pandas as pd


try:
    df_sentiment = pd.read_csv('/content/fear_greed_index.csv')
    print("Bitcoin Market Sentiment Data Loaded Successfully:")
    display(df_sentiment.head())
except FileNotFoundError:
    print("Error: 'fear_greed_index.csv' not found. Please upload the file and ensure the filename is correct.")

try:
    df_trader = pd.read_csv('/content/historical_data.csv', low_memory=False)
    print("\nHistorical Trader Data Loaded Successfully:")
    display(df_trader.head())
except FileNotFoundError:
    print("Error: 'historical_data.csv' not found. Please upload the file and ensure the filename is correct.")

print("\n--- Missing Values in df_sentiment ---")
df_sentiment.isnull().sum()

print("Converting 'date' column in df_sentiment to datetime...")
df_sentiment['date'] = pd.to_datetime(df_sentiment['date'])
df_sentiment.info()

print("Converting 'Timestamp IST' and 'Timestamp' columns in df_trader to datetime...")
df_trader['Timestamp IST'] = pd.to_datetime(df_trader['Timestamp IST'], format='%d-%m-%Y %H:%M')
df_trader['Timestamp'] = pd.to_datetime(df_trader['Timestamp'], unit='ms') # Assuming Unix timestamp for 'Timestamp' is in milliseconds
df_trader.info()

print("\n--- Missing Values in df_trader ---")
df_trader.isnull().sum()

print("Extracting date from 'Timestamp IST' in df_trader for merging...")
df_trader['date'] = df_trader['Timestamp IST'].dt.date

df_trader['date'] = pd.to_datetime(df_trader['date'])
df_trader.info()

print("Merging df_trader and df_sentiment on the 'date' column...")
df_merged = pd.merge(df_trader, df_sentiment, on='date', how='left')
print("Merged DataFrame Head:")
display(df_merged.head())

print("Info for Merged DataFrame:")
df_merged.info()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df_sentiment['value'], kde=True, bins=20)
plt.title('Distribution of Sentiment Value')
plt.xlabel('Sentiment Value')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("\n--- Summary Statistics for 'value' in df_sentiment ---")
display(df_sentiment['value'].describe())

print("\n--- Missing Values in Merged DataFrame ---")
df_merged.isnull().sum()

print("\n--- Mean Execution Price by Coin ---")
mean_execution_price_by_coin = df_merged.groupby('Coin')['Execution Price'].mean().reset_index()
display(mean_execution_price_by_coin.sort_values(by='Execution Price', ascending=False))

import matplotlib.pyplot as plt
import seaborn as sns


top_10_coins = mean_execution_price_by_coin.sort_values(by='Execution Price', ascending=False).head(10)

plt.figure(figsize=(12, 7))
sns.barplot(x='Coin', y='Execution Price', data=top_10_coins, palette='viridis', hue='Coin', legend=False)
plt.title('Top 10 Coins by Mean Execution Price')
plt.xlabel('Coin')
plt.ylabel('Mean Execution Price')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 7))
sns.scatterplot(x='value', y='Execution Price', data=df_merged, alpha=0.5)
plt.title('Relationship between Sentiment Value and Execution Price')
plt.xlabel('Sentiment Value')
plt.ylabel('Execution Price')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

correlation = df_merged['value'].corr(df_merged['Execution Price'])
print(f"Correlation between Sentiment Value and Execution Price: {correlation:.4f}")

df_btc = df_merged[df_merged['Coin'] == 'BTC']
correlation_btc = df_btc['value'].corr(df_btc['Execution Price'])
print(f"Correlation between Sentiment Value and Execution Price for BTC: {correlation_btc:.4f}")

df_eth = df_merged[df_merged['Coin'] == 'ETH']
correlation_eth = df_eth['value'].corr(df_eth['Execution Price'])
print(f"Correlation between Sentiment Value and Execution Price for ETH: {correlation_eth:.4f}")

df_paxg = df_merged[df_merged['Coin'] == 'PAXG']
correlation_paxg = df_paxg['value'].corr(df_paxg['Execution Price'])
print(f"Correlation between Sentiment Value and Execution Price for PAXG: {correlation_paxg:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


correlation_data = {
    'Coin': ['ETH', 'PAXG'],
    'Correlation Coefficient': [correlation_eth, correlation_paxg]
}

df_correlations = pd.DataFrame(correlation_data)

plt.figure(figsize=(8, 6))
sns.barplot(x='Coin', y='Correlation Coefficient', data=df_correlations, palette='viridis', hue='Coin', legend=False)
plt.title('Correlation between Sentiment Value and Execution Price for ETH and PAXG')
plt.xlabel('Coin')
plt.ylabel('Correlation Coefficient')
plt.ylim(0, 1)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

try:
    df_trader = pd.read_csv('/content/historical_data.csv', low_memory=False)
    print("\nHistorical Trader Data Loaded Successfully:")
    display(df_trader.head())
except FileNotFoundError:
    print("Error: 'historical_data.csv' not found. Please upload the file and ensure the filename is correct.")

correlations_top_10 = {}
for coin in top_10_coins['Coin']:
    df_coin = df_merged[df_merged['Coin'] == coin]
    correlation = df_coin['value'].corr(df_coin['Execution Price'])
    correlations_top_10[coin] = correlation

df_correlations_top_10 = pd.DataFrame(list(correlations_top_10.items()), columns=['Coin', 'Correlation Coefficient'])
display(df_correlations_top_10.sort_values(by='Correlation Coefficient', ascending=False))

plt.figure(figsize=(14, 7))
sns.barplot(x='Coin', y='Correlation Coefficient', data=df_correlations_top_10.sort_values(by='Correlation Coefficient', ascending=False), palette='viridis', hue='Coin', legend=False)
plt.title('Correlation between Sentiment Value and Execution Price for Top 10 Coins')
plt.xlabel('Coin')
plt.ylabel('Correlation Coefficient')
plt.ylim(-1, 1)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

top_10_coin_names = top_10_coins['Coin'].tolist()
df_top_10_sentiment = df_merged[df_merged['Coin'].isin(top_10_coin_names)]


classification_distribution = df_top_10_sentiment.groupby(['Coin', 'classification']).size().unstack(fill_value=0)


classification_distribution_prop = classification_distribution.div(classification_distribution.sum(axis=1), axis=0)

display(classification_distribution_prop)

plt.figure(figsize=(14, 8))
classification_distribution_prop.plot(kind='bar', stacked=True, colormap='viridis', figsize=(14, 8))
plt.title('Distribution of Sentiment Classifications Across Top 10 Coins (Proportion)')
plt.xlabel('Coin')
plt.ylabel('Proportion of Classification')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Classification')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

average_sentiment_value = df_top_10_sentiment.groupby('Coin')['value'].mean().reset_index()
average_sentiment_value = average_sentiment_value.sort_values(by='value', ascending=False)
print("\n--- Average Sentiment Value for Top 10 Coins ---")
display(average_sentiment_value)

trade_volume_top_10 = df_top_10_sentiment.groupby('Coin')['Size USD'].sum().reset_index()
trade_volume_top_10 = trade_volume_top_10.rename(columns={'Size USD': 'Total Trade Volume (USD)'})
display(trade_volume_top_10.sort_values(by='Total Trade Volume (USD)', ascending=False))

combined_df_sentiment_volume = pd.merge(average_sentiment_value, trade_volume_top_10, on='Coin')
display(combined_df_sentiment_volume.sort_values(by='value', ascending=False))

plt.figure(figsize=(12, 8))
sns.scatterplot(x='value', y='Total Trade Volume (USD)', data=combined_df_sentiment_volume, hue='Coin', s=200, style='Coin', palette='viridis')

for i, row in combined_df_sentiment_volume.iterrows():
    plt.text(row['value'] + 0.5, row['Total Trade Volume (USD)'], row['Coin'], fontsize=9, ha='left', va='center')

plt.title('Average Sentiment Value vs. Total Trade Volume for Top 10 Coins')
plt.xlabel('Average Sentiment Value')
plt.ylabel('Total Trade Volume (USD)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""### Time-Series Analysis for BTC: Sentiment vs. Price

"""

import matplotlib.pyplot as plt
import seaborn as sns

df_btc_time_series = df_merged[df_merged['Coin'] == 'BTC'].copy()


df_btc_daily = df_btc_time_series.groupby('date').agg({
    'value': 'mean',
    'Execution Price': 'mean'
}).reset_index()


fig, ax1 = plt.subplots(figsize=(14, 7))


sns.lineplot(x='date', y='value', data=df_btc_daily, ax=ax1, color='blue', label='Average Sentiment Value')
ax1.set_xlabel('Date')
ax1.set_ylabel('Average Sentiment Value', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')
ax1.set_title('BTC Daily Average Sentiment Value and Execution Price Over Time')


ax2 = ax1.twinx()
sns.lineplot(x='date', y='Execution Price', data=df_btc_daily, ax=ax2, color='red', label='Average Execution Price')
ax2.set_ylabel('Average Execution Price', color='red')
ax2.tick_params(axis='y', labelcolor='red')


lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left')

ax1.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## 2. Data Exploration: Initial Overview of `df_trader`

"""

print("\n--- Info for df_trader ---")
df_trader.info()

print("\n--- Descriptive Statistics for df_trader ---")
display(df_trader.describe())